import type { PatientDetail } from '@domain/entities/PatientDetail';

export const patientDetailFixture: PatientDetail = {
  id: 'a0000000-0000-0000-0000-000000000001',
  clickupTaskId: 'TASK-001',
  firstName: 'Santiago',
  lastName: 'Claiman',
  birthDate: '1960-03-18T00:00:00Z',
  documentType: 'CPF',
  documentNumber: '123.456.789-00',
  affiliateId: null,
  sex: 'MALE',
  phoneWhatsapp: '+55 (11) 91571-1717',
  contactEmail: 'santiago.claiman@example.com',
  chatIds: {
    FAMILY: '120363090000000001@g.us',
    PROVIDERS: '120363090000000002@g.us',
  },
  familyChatId: '120363090000000001@g.us',
  providersChatId: '120363090000000002@g.us',
  diagnosis: 'CID 6A02.5 Transtorno do espectro autista',
  dependencyLevel: 'SEVERE',
  clinicalSpecialty: 'ASD',
  clinicalSegments: null,
  serviceType: ['AT'],
  deviceType: null,
  additionalComments: 'TDAH severo',
  additionalCommentsUpdatedAt: '2026-08-28T14:35:00Z',
  additionalCommentsUpdatedBy: 'Coordinadora E2E',
  emergencyInstructions: 'Llamar al 107 y avisar a la madre',
  emergencyInstructionsUpdatedAt: '2026-08-29T10:00:00Z',
  emergencyInstructionsUpdatedBy: 'Coordinadora E2E',
  hasJudicialProtection: false,
  hasCud: true,
  hasConsent: true,
  insuranceInformed: null,
  insuranceVerified: null,
  cityLocality: 'São Paulo',
  province: 'SP',
  zoneNeighborhood: 'Bela Vista',
  country: 'BR',
  status: 'PENDING_ADMISSION',
  admissionStatus: 'PENDING_ADMISSION',
  onHoldReason: null,
  onHoldNote: null,
  serviceStartDate: '2026-09-01T00:00:00Z',
  insuranceVerifiedCodes: [],
  deviceTypes: [],
  needsAttention: false,
  attentionReasons: [],
  responsibles: [
    {
      id: 'r1',
      firstName: 'Luciana',
      lastName: 'Soto',
      relationship: 'MOM',
      phone: '(11) 99852-0481',
      email: 'luciana.soto@example.com',
      documentType: 'CPF',
      documentNumber: '987.654.321-00',
      isPrimary: true,
      displayOrder: 1,
      source: 'web_form',
    },
  ],
  addresses: [
    {
      id: 'addr1',
      addressType: 'primary',
      addressFormatted: 'Rua Augusta, 975 - São Paulo/SP',
      addressRaw: 'Rua Augusta 975, Consolação',
      complement: 'Torre A, Ap. 701',
      displayOrder: 1,
      lat: -23.5558,
      lng: -46.6622,
      isPrimary: true,
      neighborhood: 'Bela Vista',
      logisticsCorridor: 'Centro',
      accessNotes: 'Portaria 24h, interfone 701',
      country: 'BR',
    },
  ],
  professionals: [
    {
      id: 'prof1',
      name: 'Dr. João Alves Pereira',
      phone: '+55 (11) 97580-1332',
      email: 'joao.pereira@clinic.com',
      displayOrder: 1,
      isTeam: false,
    },
  ],
  contractedServices: [],
  createdAt: '2025-01-10T12:00:00Z',
  updatedAt: '2026-04-20T09:30:00Z',
};

export const patientDetailMinimal: PatientDetail = {
  id: 'b0000000-0000-0000-0000-000000000002',
  clickupTaskId: 'TASK-002',
  firstName: null,
  lastName: null,
  birthDate: null,
  documentType: null,
  documentNumber: null,
  affiliateId: null,
  sex: null,
  phoneWhatsapp: null,
  contactEmail: null,
  chatIds: {},
  familyChatId: null,
  providersChatId: null,
  diagnosis: null,
  dependencyLevel: null,
  clinicalSpecialty: null,
  clinicalSegments: null,
  serviceType: null,
  deviceType: null,
  additionalComments: null,
  emergencyInstructions: null,
  emergencyInstructionsUpdatedAt: null,
  emergencyInstructionsUpdatedBy: null,
  additionalCommentsUpdatedAt: null,
  additionalCommentsUpdatedBy: null,
  hasJudicialProtection: null,
  hasCud: null,
  hasConsent: null,
  insuranceInformed: null,
  insuranceVerified: null,
  cityLocality: null,
  province: null,
  zoneNeighborhood: null,
  country: 'AR',
  status: null,
  admissionStatus: 'DONE',
  onHoldReason: null,
  onHoldNote: null,
  serviceStartDate: null,
  insuranceVerifiedCodes: [],
  deviceTypes: [],
  needsAttention: false,
  attentionReasons: [],
  responsibles: [],
  addresses: [],
  professionals: [],
  contractedServices: [],
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};
